### PR TITLE
feat(plugin): smart links (#23)

### PR DESCRIPTION
**Pull request by DragonIsGone**
currently incomplete
----

- [x] functionality
- [x] wxt [storage migration](https://wxt.dev/guide/extension-apis/storage.html#running-migrations) (from `homepageSwitcher` to `smartLinks`)

This is an improvement over the current "Homepage Switcher" plugin
> The logo will switch to existing Schoolbox homepage when available

It has all existing functionality plus:
- works for all other schoolbox links
- customisable settings in popup

### CODE REVIEW

**Comment by 42Willow** [comment]
Customisable settings will be added under a topic branch and will not be included in this PR

I will rebase the relevant commits onto the new branch and force push

**Comment by 42Willow** [comment]
better

**Comment by 42Willow** [comment]
This actually needs to be tested before it is squashed and merged, I have zero confidence in my skill

**Comment by BC-548** [comment]
Done

**Comment by 42Willow** [comment]
UH did you test it?

**Comment by 42Willow** [comment]
I'm still trying to figure out how to test the storage migration

**Comment by 42Willow** [comment]
ok slight issue, the migration is stuffed - need to restructure the settings

**Comment by 42Willow** [comment]
https://github.com/schooltape/schooltape/tree/refactor/homepageSwitcher this will be tracked here now

**Pull request merged**
